### ISSUE TITLE
To-do list :D

### ISSUE THREAD

**Issue by igorwastaken** [apenasigordev/Sarah-Bot#1]
# Things & Features we need for future updates.

* [ ] More Valorant & Others games commands
* [ ] An economy system (maybe for a future RPG project)
* [ ] Fix permissions (People got some errors like [This one](https://cdn.discordapp.com/attachments/1113532861769846877/1168694206009716836/image.png))
* [x] Make an "About The Project", to show information about the bot, etc.

Am too lazy to put more things, but maybe tomorrow i'll do that.
